# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4971e4a4baeed47f6f1402de48bce36b2dfa57befffed8996436c4ddf6aeaa8c5a3d25f76cedf509ca04e5484ae96602236cd5f8a469b24dce443778b1dfb00d

test:
  secret_key_base: 9fb7fd836c28736a4fa95eaeb57906edf986aa282470893c910560f6ba639b277810ab55ffe17f0572e5e87b30ab5c962f7e944cced75c1f7c2bd63801b8fa9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
